CREATE TABLE IF NOT EXISTS produto (
    codigo SERIAL NOT NULL,
    id VARCHAR(40) PRIMARY KEY NOT NULL,
    nome TEXT,
    jclasses TEXT,
    jespecificacoes TEXT,
    jvariacoes TEXT,
    tipo TEXT NOT NULL DEFAULT 'produto',
    empresa INTEGER,
    descricao TEXT,
    grupo INTEGER,
    categoria INTEGER,
    classe INTEGER,
    segmento INTEGER,
    setor INTEGER,
    codbarras TEXT,
    url TEXT,
    memorando TEXT,
    preco REAL,
    custo REAL,
    estoque REAL,
    maximo REAL,
    minimo REAL,
    ideal REAL,
    ativo BOOLEAN NOT NULL DEFAULT true,
    referencia TEXT,
    abc TEXT NOT NULL DEFAULT ' ',
    composicao BOOLEAN NOT NULL DEFAULT false,
    medida REAL,
    und TEXT NOT NULL DEFAULT 'un',
    componente BOOLEAN NOT NULL DEFAULT true,
    compra BOOLEAN NOT NULL DEFAULT true,
    venda BOOLEAN NOT NULL DEFAULT true,
    preco_compra REAL,
    und_compra TEXT,
    und_venda TEXT,
    fator_compra REAL,
    fator_venda REAL,
    nometemp TEXT,
    redireciona varchar(40),
    created_at TIMESTAMP with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
    
);

alter table produto 
add FOREIGN KEY (redireciona) REFERENCES produto(id);