CREATE TABLE IF NOT EXISTS pessoa (
	codigo serial NOT NULL,
	id varchar(40) NOT NULL,
	"data" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dataalteracao timestamp NULL,
	nome text NULL,
	tipopessoa text NULL DEFAULT 'FISICA'::text,
	grupo int4 NULL,
	perfil int4 NULL,
	nacionalidade int4 NULL,
	observacoes int4 NULL,
	telefone text NULL,
	email text NULL,
	url text NULL,
	endereco text NULL,
	cidade int4 NULL,
	uf text NULL,
	cep text NULL,
	credencial text NULL,
	senha text NULL,
	inscricao_federal text NULL,
	inscricao_estadual text NULL,
	abc text NULL,
	credito float4 NULL,
	ativo bool NOT NULL DEFAULT true,
	bairro text NULL,
	cliente bool NULL,
	fornecedor bool NULL,
	funcionario bool NULL,
	motorista bool NULL,
	transportador bool NULL,
	transportadora bool NULL,
	contador bool NULL,
	medico bool NULL,
	paciente bool NULL,
	vendedor bool NULL,
	avatar varchar NULL,
	created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	alterado timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	id_empresa varchar(40) NOT NULL,
	id_tipo_pessoa varchar(40) NOT NULL DEFAULT 'INDEFINIDO'::character varying,
	id_grupo_pessoa varchar(40) NOT NULL DEFAULT 'INDEFINIDO'::character varying,
	id_regiao_pessoa varchar(40) NOT NULL DEFAULT 'INDEFINIDO'::character varying,
	id_perfil_pessoa varchar(40) NOT NULL DEFAULT 'INDEFINIDO'::character varying,
	id_nacionalidade_pessoa varchar(40) NOT NULL DEFAULT 'INDEFINIDO'::character varying,
	id_identificacao varchar(40) NOT NULL,
	id_tipo_identificacao varchar(40) NOT NULL,
	id_status varchar(40) NOT NULL DEFAULT '54c18fe3-ce77-5184-8394-330e1ae3d7ae'::character varying,
	id_email varchar(40) NOT NULL,
	razao_social varchar NOT NULL,
	id_telefone varchar(40) NOT NULL,
	id_celular varchar(40) NULL,
	id_endereco_principal varchar(40) NOT NULL REFERENCES ENDERECO(ID) DEFAULT 'INDEFINIDO',
	id_endereco_financeiro varchar(40) NULL,
	id_endereco_comercial varchar(40) NULL,
	id_endereco_cobranca varchar(40) NULL,
	CONSTRAINT pessoa_pkey PRIMARY KEY (id),
	CONSTRAINT pessoa_id_celular_fkey FOREIGN KEY (id_celular) REFERENCES contato(id),
	CONSTRAINT pessoa_id_email_fkey FOREIGN KEY (id_email) REFERENCES contato(id),
	CONSTRAINT pessoa_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES empresa(id),
	CONSTRAINT pessoa_id_endereco_cobranca_fkey FOREIGN KEY (id_endereco_cobranca) REFERENCES endereco(id),
	CONSTRAINT pessoa_id_endereco_comercial_fkey FOREIGN KEY (id_endereco_comercial) REFERENCES endereco(id),
	CONSTRAINT pessoa_id_endereco_financeiro_fkey FOREIGN KEY (id_endereco_financeiro) REFERENCES endereco(id),
	CONSTRAINT pessoa_id_endereco_principal_fkey FOREIGN KEY (id_endereco_principal) REFERENCES endereco(id),
	CONSTRAINT pessoa_id_grupo_pessoa_fkey FOREIGN KEY (id_grupo_pessoa) REFERENCES grupo_pessoa(id),
	CONSTRAINT pessoa_id_identificacao_fkey FOREIGN KEY (id_identificacao) REFERENCES identificacao(id),
	CONSTRAINT pessoa_id_nacionalidade_pessoa_fkey FOREIGN KEY (id_nacionalidade_pessoa) REFERENCES perfil_pessoa(id),
	CONSTRAINT pessoa_id_perfil_pessoa_fkey FOREIGN KEY (id_perfil_pessoa) REFERENCES perfil_pessoa(id),
	CONSTRAINT pessoa_id_regiao_pessoa_fkey FOREIGN KEY (id_regiao_pessoa) REFERENCES regiao_pessoa(id),
	CONSTRAINT pessoa_id_status_fkey FOREIGN KEY (id_status) REFERENCES status_pessoa(id),
	CONSTRAINT pessoa_id_telefone_fkey FOREIGN KEY (id_telefone) REFERENCES contato(id),
	CONSTRAINT pessoa_id_tipo_identificacao_fkey FOREIGN KEY (id_tipo_identificacao) REFERENCES tipo_identificacao(id),
	CONSTRAINT pessoa_id_tipo_pessoa_fkey FOREIGN KEY (id_tipo_pessoa) REFERENCES tipo_pessoa(id)
);

create table if not exists empresa  (
    id  VARCHAR(40) not null PRIMARY key,
    codigo serial,
	created TIMESTAMP with TIME ZONE not null default current_timestamp,
    nome VARCHAR not null,
    fantasia VARCHAR not null,
    endereco varchar not null,
    cidade varchar not null,
    estado varchar not null,
    id_telefone varchar(40) references contato(id),
    id_email varchar(40) references contato(id),
    id_cnpj varchar(40) references identificacao(id),
    id_user VARCHAR(40)  references users(id),
    id_responsavel varchar(40) references pessoa(id),
    id_empresa_cadastro varchar(40) null references empresa(id),
    id_empresa_pessoas varchar(40) null references empresa(id),
    id_empresa_produtos varchar(40) null references empresa(id)
    );
    
insert into empresa 
(id, codigo, nome, fantasia, endereco, cidade, estado)
values ('0190efad-d52a-7e41-8337-e07796f3860b', 1, 'DEMONSTRAÇÃO', 'Empresa Demonstração', 'Av Beira Rio', 'Uba', 'MG');

CREATE TABLE enviar_email (
	id varchar(40) NOT NULL,
	id_email varchar(40) NOT NULL,
	body text NULL,
	CONSTRAINT enviar_email_pkey PRIMARY KEY (id)
);