INSERT INTO produtos
VALUES (NULL,'X-Burguer', 'Pão, hambúrguer bovino, queijo, alface, tomate e maionese especial', 1200,
        'https://picsum.photos/150?random=1'),
       (NULL,'X-Salada', 'Pão, hambúrguer bovino, queijo, alface, tomate, cebola e maionese caseira', 1500,
        'https://picsum.photos/150?random=2'),
       (NULL,'X-Bacon', 'Pão, hambúrguer bovino, queijo, bacon crocante e molho barbecue', 1800,
        'https://picsum.photos/150?random=3'),
       (NULL,'X-Egg', 'Pão, hambúrguer bovino, queijo, ovo frito, alface, tomate e maionese', 1700,
        'https://picsum.photos/150?random=4'),
       (NULL,'X-Frango', 'Pão, filé de frango grelhado, queijo, alface, tomate e molho de iogurte', 1600,
        'https://picsum.photos/150?random=5'),
       (NULL,'X-Calabresa', 'Pão, calabresa acebolada, queijo, tomate e maionese de alho', 1800,
        'https://picsum.photos/150?random=6'),
       (NULL,'X-Tudo', 'Pão, hambúrguer bovino, queijo, ovo, bacon, calabresa, alface, tomate e molho especial', 2200,
        'https://picsum.photos/150?random=7'),
       (NULL,'Cheeseburger', 'Pão, hambúrguer bovino e queijo cheddar derretido', 1000,
        'https://picsum.photos/150?random=8'),
       (NULL,'X-Duplo', 'Pão, dois hambúrgueres bovinos, queijo, alface, tomate e molho secreto', 2000,
        'https://picsum.photos/150?random=9'),
       (NULL,'X-Veggie', 'Pão integral, hambúrguer de grão-de-bico, alface, tomate, cenoura ralada e maionese vegana', 1900,
        'https://picsum.photos/150?random=10'),
       (NULL,'Hot Dog', 'Pão de cachorro-quente, salsicha, ketchup, mostarda e batata palha', 900,
        'https://picsum.photos/150?random=11'),
       (NULL,'Hot Dog Especial', 'Pão de cachorro-quente, duas salsichas, queijo, bacon e molho cheddar', 1500,
        'https://picsum.photos/150?random=12'),
       (NULL,'Sanduíche Natural', 'Pão integral, peito de peru, queijo branco, alface, tomate e molho de ervas', 1100,
        'https://picsum.photos/150?random=13'),
       (NULL,'Torrada Mista', 'Pão de forma, presunto, queijo e orégano, tostado na chapa', 800,
        'https://picsum.photos/150?random=14'),
       (NULL,'Wrap de Frango', 'Tortilla recheada com frango grelhado, alface, tomate e molho ranch', 1300,
        'https://picsum.photos/150?random=15'),
       (NULL,'Wrap Vegano', 'Tortilla recheada com tofu, legumes grelhados e molho tahine', 1400,
        'https://picsum.photos/150?random=16'),
       (NULL,'Hambúrguer Gourmet', 'Pão brioche, hambúrguer de picanha, queijo brie, rúcula e cebola caramelizada', 2500,
        'https://picsum.photos/150?random=17'),
       (NULL,'Cachorro-Quente Gourmet', 'Pão artesanal, salsicha artesanal, molho cheddar e cebola crispy', 1700,
        'https://picsum.photos/150?random=18'),
       (NULL,'Mini Hambúrguer', 'Pão, mini hambúrguer bovino, queijo e ketchup', 700, 'https://picsum.photos/150?random=19'),
       (NULL,'Sanduíche de Mortadela', 'Pão francês, mortadela fatiada e queijo derretido', 1200,
        'https://picsum.photos/150?random=20'),
       (NULL,'Pão de Alho', 'Pão recheado com manteiga de alho e queijo parmesão gratinado', 800,
        'https://picsum.photos/150?random=21'),
       (NULL,'Croissant de Presunto e Queijo', 'Croissant recheado com presunto e queijo, assado na hora', 1500,
        'https://picsum.photos/150?random=22'),
       (NULL,'Pão na Chapa', 'Pão francês crocante com manteiga derretida na chapa', 500,
        'https://picsum.photos/150?random=23'),
       (NULL,'Bauru', 'Pão francês, rosbife, queijo derretido, tomate e orégano', 1300,
        'https://picsum.photos/150?random=24'),
       (NULL,'Tapioca de Frango', 'Tapioca recheada com frango desfiado, queijo coalho e molho de pimenta', 1200,
        'https://picsum.photos/150?random=25'),
       (NULL,'Tapioca de Queijo', 'Tapioca recheada com queijo coalho e orégano', 1000,
        'https://picsum.photos/150?random=26'),
       (NULL,'Panini Italiano', 'Panini com salame, queijo provolone, rúcula e tomate seco', 1600,
        'https://picsum.photos/150?random=27'),
       (NULL,'Bagel de Salmão', 'Bagel recheado com salmão defumado, cream cheese e cebolinha', 2000,
        'https://picsum.photos/150?random=28'),
       (NULL,'Queijo Quente', 'Pão de forma com queijo derretido e crocante na chapa', 700,
        'https://picsum.photos/150?random=29'),
       (NULL,'Sanduíche de Pernil', 'Pão francês, pernil desfiado, molho de cebola e pimentão', 1500,
        'https://picsum.photos/150?random=30');
